### PR TITLE
Adjust naming to try to standardize a simple format

### PR DESCRIPTION
**Pull request by gparvin**
Let's use naming that is simple and easy for others to pick up quickly.  Does this naming work well?  Summary:
- label changed to entity
- removed replicas
- Switched from the label being a kubernetes resource to a basic value like API, Custom Resource, etc
- the name now matches an actual name of the resource.

### CODE REVIEW

**Comment by bjoydeep** [comment]
@gparvin Thank You! This taking good shape... A few observations and questions.

```
  <key id="userCreated" for="node" attr.name="userCreated" attr.type="boolean" />
  <key id="onHub" for="node" attr.name="onHub" attr.type="boolean" />
  <key id="onManaged" for="node" attr.name="onManaged" attr.type="boolean" />
  <key id="name" for="node" attr.name="name" attr.type="string" />
  <key id="entity" for="node" attr.name="entity" attr.type="string" />
  <key id="type" for="node" attr.name="type" attr.type="string" />
  <key id="namespace" for="node" attr.name="namespace" attr.type="string" />
  ```
userCreated makes complete sense:
1.   Should this be there for all nodes? 
2.   Should we make `createdBy` and enum it instead. 
3.   or just keep it simple - if its directly created by user, its Yes. Else its false? It is assumed/implied that its created by ACM Machinery otherwise.

onHub and onManaged should be separate - like what you did - because both can be true. I overlooked that one while using a location tag.

entity and type are the ones which I am little confused about. 
1. entity list in your XML are - API, Custom Resource and Intermediate Resource. Aren't Custom Resource by definition APIs as well? CRs Could be internal or external though. Or directly manipulated vs not.
2. You have not used types for every node. What is the logic

**Comment by gparvin** [comment]
Thanks @bjoydeep I'll review this and make some updates.  One question I have is the difference between Custom Resource and Intermediate Resource.  Would an intermediate resource just be a Custom Resource with user Created set to false?

**Comment by bjoydeep** [comment]
@gparvin `Would an intermediate resource just be a Custom Resource with user Created set to false` is exactly what I was thinking!
Or is there another better way to categorize? I am totally open. I was thinking from user/customer perspective, they give inputs (APIs) to the process- and then the process produces artifacts (intermediate resources, WIP etc) before the final outcome.

**Comment by gparvin** [comment]
> @gparvin `Would an intermediate resource just be a Custom Resource with user Created set to false` is exactly what I was thinking! Or is there another better way to categorize? I am totally open. I was thinking from user/customer perspective, they give inputs (APIs) to the process- and then the process produces artifacts (intermediate resources, WIP etc) before the final outcome.

Right, I expect we need both scenarios - though I think some naming guidelines would help along with the example.  Maybe we need to add these thoughts to a Naming.md

**Comment by gparvin** [comment]
Added more things to comment on and trying to flush out the entity definitions in a new naming doc

**Comment by gparvin** [comment]
Added more things to comment on and trying to flush out the entity definitions in a new naming doc

**Comment by bjoydeep** [comment]
Thanks @gparvin . Lets go ahead with this. Thanks for adding that doc. I still have open questions - but that is not something we will resolve today. As we gain more experience - by looking at the other KGs being added and more engineers engaging, we will be wiser. But this is a great start.

**Review by bjoydeep — APPROVED** [review]

**Pull request merged**
