### PR TITLE
add foundation knowledge graphs

### PR DESCRIPTION
**Pull request by elgnay**
The related issue: https://issues.redhat.com/browse/ACM-8635

### CODE REVIEW

**Comment by bjoydeep** [comment]
Thanks @elgnay . I am checking this out carefully.

**Comment by bjoydeep** [comment]
@elgnay can you please confirm that these all are indeed created by the User  - `match(p:Users)-[r:CREATES]-(q) where not q.name in ['MCO-CR'] return p,r,q`
And out of curiosity, does the cover all the nodes that you added: `match(p:Users)-[]-(q)-[*3]-(r)  where not q.name in ['MCO-CR'] return p,q,r` - You can adjust 3 to 4 or 5 and see. It symbolises the number of hops. In this query MCO-CR leaks - need to see why.

**Comment by elgnay** [comment]
The `ClusterManagementAddOn` is not created by User. There is bug in the python script when building the edges. It only considers the `name` and `entity` of a node. There may exist multiple nodes with same `name` and `entity` but different `type`, like `ManagedClusterAddOn` and `ClusterManagementAddOn`.

**Comment by bjoydeep** [comment]
Yes, I see the bug. Thanks for pointing this out. I will fix it asap.
Some points for consideration - 

1. Basically we made an implicit assumption that entity.name should be unique. That plays out visually very nicely as well. WDYT? In your case, it just means tweaking the names of a few entities. 
2. Another convention we were adopting. API entity type is which users interact with. If user does not interact with it, it should be IntermediateResource of type Controller or CR. WDYT?

@gparvin for your thoughts as well.
Irrespective of what we decide above @elgnay , the bug will be fixed.

**Comment by bjoydeep** [comment]
@elgnay  - the defect is fixed now. Could you recheck now please.

**Comment by elgnay** [comment]
@bjoydeep The graphs have been updated. Please review them one more time. Thanks!

**Comment by bjoydeep** [comment]
2 questions:

1. is the Processor with name klusterletAgent supposed to represent both the registration and work agent on the managed cluster. 
2. you raise a very interesting question the way you use the `type` attribute for `entity API` .  In some examples, it has the CR name - like ManagedCluster, ManagedClusterAddon, ClusterManagementAddon, APIServer (in these examples, the name of the API is a little cryptic) and in another instance type is a Custom Resource and name is AddonDeploymentConfig-CR. I would probably vote that for entity type = API, we should use type= CR and name = CR Name. But let us discuss.

**Comment by elgnay** [comment]
>     1. is the Processor with name klusterletAgent supposed to represent both the registration and work agent on the managed cluster.

Yes.

**Comment by elgnay** [comment]
@bjoydeep The foundation graphs have been updated with the latest conversion. Please take a look.

**Review by bjoydeep — APPROVED** [review]

**Pull request merged**
