### PR TITLE
adding more to obs flow

### PR DESCRIPTION
**Pull request by bjoydeep**
This adds to the obs flow - 
shows how data is shown from grafana
shows how the entire install process from obs works
and combined with the other related subgraphs - tells a much bigger picture.

@douglascamata can you give this a review please.

### CODE REVIEW

**Comment by douglascamata** [comment]
@bjoydeep: I think an important missing part in the knowledge graph is the Thanos Ruler and its relationships:

* Is **created by** ObservatoriumOperator.
* **Sends** alerts to Alert-manager.
* **Queries** the Thanos Querier.
* Is **queried** by Thanos Querier.
* **Stores** in the Thanos Object Store.
* **Uses** Thanos Object Store Secret.

Additional feedback

* Rename Thanos Store to Thanos Store Gateway to avoid confusion with other concepts in Thanos.
* What's the criteria to decide wether a relationship A -> B is active (A watches B) or passive (A is watched by B)? This difference got me slightly confused a few times because it's difficult to read the "by" word in the graph view, while it's easy to quickly scan and identify the "watches" word. I think it would be cool to standardize on the active relationship.

**Comment by bjoydeep** [comment]
@douglascamata addressed all points including using `WATCHES` instead of `WATCHEDBY`

**Review by douglascamata — APPROVED** [review]
LGTM :shipit:

**Review by gparvin — APPROVED** [review]

**Pull request merged**
