### PR TITLE
Redo the grc test sample to match new ontology

### PR DESCRIPTION
**Pull request by gparvin**
This is a big simplification to the GRC tests sample.  It may be over simplified now, but it uses the ontology we discussed and provides the basic knowledge for how the testing in GRC works.

### CODE REVIEW

**Comment by bjoydeep** [comment]
@gparvin this looks much cleaner - thank you! 

Question - if we run `match(p:Repository) return(p)` and look at the `text` view and not `graph` view we will see multiple repositories. Can you cross check whether they all need to exist or can some of them be merged. You are the domain expert, so you can make the determination.

Observation - 
The moment we try to `merge` 2 nodes, we will see that not only entity but all other attr for that entity should match. This can be an issue using `tags`. The moment I add a new tag to an entity, even I intend to use the same entity, a new one will be created. Going forward, we will have to see how big a problem this can be. Do not need to overthink as of now.

**Comment by gparvin** [comment]
> @gparvin this looks much cleaner - thank you!
> 
> Question - if we run `match(p:Repository) return(p)` and look at the `text` view and not `graph` view we will see multiple repositories. Can you cross check whether they all need to exist or can some of them be merged. You are the domain expert, so you can make the determination.
> 
> Observation - The moment we try to `merge` 2 nodes, we will see that not only entity but all other attr for that entity should match. This can be an issue using `tags`. The moment I add a new tag to an entity, even I intend to use the same entity, a new one will be created. Going forward, we will have to see how big a problem this can be. Do not need to overthink as of now.

I will merge them.  You are correct that I have multiple entities that represent the same thing.

**Comment by bjoydeep** [comment]
LGTM

**Review by bjoydeep — APPROVED** [review]

**Pull request merged**
